name: 'dbt_olist'
version: '1.0.0'

# Khớp với tên trong file profiles.yml của bạn
profile: 'olist_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Cấu hình phân lớp dữ liệu (Data Layering)
models:
  dbt_olist:
    +materialized: view
    
    staging:
      +schema: staging
    
    intermediate:
      +schema: intermediate
      +materialized: view
      #+materialized: ephemeral # giống như CTE, không tạo bảng vật lý, chỉ dùng trong quá trình chạy model

    marts:
      +schema: marts
      +materialized: table